import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Analytics } from "@vercel/analytics/react"
import {ClerkProvider} from "@clerk/nextjs";
import React from "react";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hekta E-Commerce",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider >
    <html lang="en">
      <link rel="icon" href="favicon.png"></link>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/all.min.css"></link>
      <body className={inter.className}>
      <header>
        <Navbar/>
      </header>
      <div className="pt-28">
         
        {children}
        </div>
        <Analytics />
        <Footer/>
        </body>
    </html>
    </ClerkProvider>
  );
}
