import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Analytics } from "@vercel/analytics/react"
import {ClerkProvider} from "@clerk/nextjs";
import React from "react";
import { ToastContainer, Slide } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hekta E-Commerce",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider >
    <html lang="en">
      <link rel="icon" href="favicon.png"></link>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/all.min.css"></link>
      <body className={inter.className}>
      <header>
        <Navbar/>
      </header>
      <ToastContainer
        position="bottom-center" // Set to bottom
        autoClose={3000} // Close after 3 seconds
        hideProgressBar={false} // Show progress bar
        newestOnTop={false} 
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="light"
        transition={Slide}
      />
      <div className="pt-28">
         
        {children}
        </div>
        <Analytics />
        <Footer/>
        </body>
    </html>
    </ClerkProvider>
  );
}
